-- Rust language groups (.rs) — vimscript syntax + Treesitter

local M = {}

function M.get(p, groups, styles)
	return {
		-- Legacy rust.vim syntax groups
		rustKeyword = { fg = p.crimson },
		rustReservedKeyword = { fg = p.crimson },
		rustStorage = { fg = p.crimson },
		rustStructure = { fg = p.crimson },
		rustPubScopeCrate = { fg = p.crimson },
		rustModPath = { fg = p.gold },
		rustModPathSep = { fg = p.color400 },
		rustIdentifier = { fg = p.color200 },
		rustFuncName = { fg = p.primary },
		rustFuncCall = { fg = p.primary },
		rustMacro = { fg = p.violet, style = "bold" },
		rustMacroVariable = { fg = p.violet },
		rustTrait = { fg = p.gold },
		rustDeriveTrait = { fg = p.gold },
		rustEnum = { fg = p.gold },
		rustEnumVariant = { fg = p.violet },
		rustType = { fg = p.gold },
		rustSelf = { fg = p.color300, style = styles.italic },
		rustSigil = { fg = p.frost },
		rustOperator = { fg = p.frost },
		rustArrowCharacter = { fg = p.frost },
		rustQuestionMark = { fg = p.crimson },
		rustLifetime = { fg = p.amber, style = styles.italic },
		rustLabel = { fg = p.seafoam },
		rustString = { fg = p.sage },
		rustStringRaw = { fg = p.sage },
		rustCharacter = { fg = p.sage },
		rustEscape = { fg = p.rust },
		rustFormat = { fg = p.coral },
		rustSpecial = { fg = p.rust },
		rustComment = { fg = p.color400 },
		rustCommentLine = { fg = p.color400 },
		rustCommentBlock = { fg = p.color400 },
		rustCommentLineDoc = { fg = p.color400 },
		rustCommentBlockDoc = { fg = p.color400 },
		rustAttribute = { fg = p.amber, style = styles.italic },
		rustDerive = { fg = p.amber, style = styles.italic },
		rustConditional = { fg = p.tide },
		rustRepeat = { fg = p.tide },
		rustBoolean = { fg = p.tide },
		rustConstant = { fg = p.tide },
		rustDecNumber = { fg = p.violet },
		rustHexNumber = { fg = p.violet },
		rustOctNumber = { fg = p.violet },
		rustBinNumber = { fg = p.violet },
		rustFloat = { fg = p.violet },

		-- Rust Treesitter
		["@keyword.rust"] = { fg = p.crimson },
		["@keyword.import.rust"] = { fg = p.crimson },
		["@keyword.function.rust"] = { fg = p.crimson },
		["@keyword.return.rust"] = { fg = p.crimson },
		["@type.rust"] = { fg = p.gold },
		["@type.builtin.rust"] = { fg = p.amber },
		["@type.definition.rust"] = { fg = p.gold },
		["@function.rust"] = { fg = p.primary },
		["@function.builtin.rust"] = { fg = p.primary },
		["@function.macro.rust"] = { fg = p.primary, style = "bold" },
		["@constant.rust"] = { fg = p.tide },
		["@constant.builtin.rust"] = { fg = p.tide },
		["@variable.builtin.rust"] = { fg = p.color300, style = styles.italic },
		["@module.rust"] = { fg = p.gold },
		["@constructor.rust"] = { fg = p.primary },
		["@attribute.rust"] = { fg = p.amber, style = styles.italic },
		["@label.rust"] = { fg = p.amber, style = styles.italic },
		["@punctuation.special.rust"] = { fg = p.coral },
	}
end

return M
