-- Generic Treesitter captures

local M = {}

function M.get(p, groups, styles)
	return {
		["@variable"] = { fg = p.color200 },
		["@property"] = { fg = p.color300 },
		["@variable.builtin"] = { fg = p.color300 },
		["@variable.parameter"] = { fg = p.color200, style = styles.italic },
		["@variable.member"] = { fg = p.color500 },
		["@variable.object.property"] = { fg = p.color500 },
		["@constant"] = { link = "Constant" },
		["@constant.builtin"] = { fg = p.violet },
		["@constant.macro"] = { fg = p.violet, style = "bold" },
		["@function"] = { link = "Function" },
		["@function.call"] = { link = "Function" },
		["@function.builtin"] = { fg = p.crimson },
		["@function.macro"] = { fg = p.violet, style = "bold" },
		["@keyword"] = { link = "Keyword" },
		["@keyword.function"] = { fg = p.crimson },
		["@keyword.import"] = { fg = p.violet },
		["@keyword.operator"] = { link = "Operator" },
		["@keyword.return"] = { link = "Keyword" },
		["@keyword.coroutine"] = { fg = p.tide },
		["@keyword.export"] = { fg = p.crimson },
		["@parameter"] = { fg = p.color200 },
		["@method"] = { fg = p.gold },
		["@operator"] = { fg = p.frost },
		["@punctuation.delimiter"] = { fg = p.color400 },
		["@punctuation.bracket"] = { fg = p.color400 },
		["@string"] = { link = "String" },
		["@string.documentation"] = { fg = p.color400 },
		["@string.regexp"] = { fg = p.coral },
		["@string.escape"] = { fg = p.rust },
		["@tag"] = { fg = p.sage },
		["@tag.attribute"] = { fg = p.gold, style = styles.italic },
		["@text"] = { fg = p.color200 },
		["@text.title"] = { fg = p.primary, style = "bold" },
		["@type"] = { fg = p.gold },
		["@type.builtin"] = { fg = p.amber },
		["@type.qualifier"] = { fg = p.crimson },
		["@type.definition"] = { fg = p.crimson },
		["@label"] = { fg = p.seafoam },
		["@conditional"] = { fg = p.tide },
		["@repeat"] = { fg = p.tide },
		["@storageclass"] = { fg = p.crimson },
		["@structure"] = { fg = p.crimson },
		["@include"] = { fg = p.violet },
		["@exception"] = { fg = p.tide },
		["@comment"] = { fg = p.color400 },
		["@comment.error"] = { fg = p.error },
		["@comment.warning"] = { fg = p.warning },
		["@comment.hint"] = { fg = p.success },
		["@comment.todo"] = { fg = p.gold, style = "bold" },
	}
end

return M
