-- Editor UI sections (cursor, background, statusline, menus, search, splits, etc.)

local M = {}

function M.get(p, groups, styles)
	return {
		LineNr = { fg = p.color400 },
		CursorLine = { bg = p.none, fg = p.rust },
		CursorLineNr = { fg = p.crimson },
		CursorColumn = { bg = p.color800 },
		Cursor = { fg = p.color200, bg = p.placeholder },
		ColorColumn = { bg = p.color600 },
		Conceal = { fg = p.color200, bg = p.none },
		DiffAdd = { bg = p.color700 },
		DiffChange = { fg = p.color200, bg = p.color700 },
		DiffDelete = { bg = p.color700 },
		DiffText = { bg = p.color700 },
		Directory = { fg = p.color300, bg = p.none },
		ErrorMsg = { fg = p.error, style = "bold" },
		FloatBorder = { fg = groups.border },
		FloatTitle = { fg = p.color200 },
		FoldColumn = { fg = p.color200 },
		Folded = { fg = p.color200, bg = groups.panel },
		IncSearch = { fg = p.color200, bg = p.color600 },
		MatchParen = { fg = p.color200, bg = p.color700 },
		ModeMsg = { fg = p.color200 },
		MoreMsg = { fg = p.color200 },
		NonText = { fg = p.color500 },
		Normal = { fg = p.color300, bg = p.color700 },
		NormalFloat = { fg = p.color200, bg = p.color700 },
		NormalNC = { fg = p.color200, bg = p.color700 },
		Pmenu = { fg = p.color200, bg = p.color700 },
		PmenuSbar = { bg = p.color700 },
		PmenuSel = { fg = p.color200, bg = p.color400 },
		PmenuThumb = { bg = p.color600 },
		Question = { fg = p.warning },
		Search = { fg = p.color200, bg = p.color600 },
		SignColumn = { fg = p.color200, bg = p.none },
		SpecialKey = { fg = p.color200 },
		SpellBad = { sp = p.error, style = "undercurl" },
		SpellCap = { sp = p.color300, style = "undercurl" },
		SpellLocal = { sp = p.warning, style = "undercurl" },
		SpellRare = { sp = p.color300, style = "undercurl" },
		StatusLine = { fg = p.color200, bg = styles.float_background },
		StatusLineNC = { fg = p.color200, bg = styles.background },
		TabLine = { fg = p.color200 },
		TabLineFill = { bg = p.color800 },
		TabLineSel = { fg = p.color200, bg = p.color800 },
		Title = { fg = p.color200 },
		VertSplit = { fg = groups.border },
		Visual = { fg = p.color200, bg = p.color600 },
		WarningMsg = { fg = p.warning },
		Whitespace = { fg = p.color600 },
		WildMenu = { link = "IncSearch" },
		WinSeparator = { fg = p.color600, bg = p.color700 },
	}
end

return M
